[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "web"
command = "npm run build && npm start"

[environments.production]
DATABASE_URL = { reference = "DATABASE_URL" }
PORT = { default = "3000" }